[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pokecatch_cli_game"
version = "1.0.0"
description = "A terminal-based Pokemon catching game"
readme = "Readme.md"
requires-python = ">=3.8"
dependencies = [
    "term-image",
    "Pillow"
]

[project.scripts]

pokecatch = "pokecatch.__main__:main"

[tool.setuptools.packages.find]
include = ["pokecatch*"]

[tool.setuptools.package-data]
pokecatch = ["sprites/pokemons/*.png", "data/*.json"]